package challenge.webside.authorization;

public enum Action {
    CREATE_CHALLENGE,
    EDIT_CHALLENGE, 
    SUBSCRIBE_CHALLENGE, 
    DELETE_CHALLENGE,
    CLOSE_CHALLENGE,
    VOTE_FOR_CHALLENGE,
    ADD_STEPS,
    THROW_CHALLENGE_FOR_USER,
    THROW_CHALLENGE_DEF, 
    ACCEPT_CHALLENGE_DEF, 
    WATCH_UNACCEPTED_CHALLENGES,
    WATCH_VOTES,
    EDIT_PROFILE,
    ADD_FRIEND
}
